import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

// Casual Office — casualoffice.org.
// Astro static build. Output goes to dist/; GitHub Pages serves that
// directory via .github/workflows/pages.yml.
//
// Sitemap is auto-generated by @astrojs/sitemap from the routes Astro
// emits. Lastmod is filled in from each page's frontmatter or build time.
// The robots.txt at public/robots.txt references sitemap-index.xml.
export default defineConfig({
  site: 'https://casualoffice.org',
  trailingSlash: 'always',
  // "Casual Editor" was renamed to "Casual Docs"; the product page moved
  // from /casual-editor/ to /casual-docs/. Keep the old path alive so
  // already-indexed URLs and inbound links resolve instead of 404ing.
  // Astro emits a static redirect page (meta-refresh + canonical) here.
  redirects: {
    '/casual-editor/': '/casual-docs/',
  },
  // Markdown code blocks use Shiki for syntax highlighting. Astro's
  // default is `github-dark` which renders dark-bg + dark-fg on our
  // light theme — every fenced ```code``` block in /docs/ becomes
  // unreadable. `github-light` matches the surrounding light surface.
  markdown: {
    shikiConfig: {
      theme: 'github-light',
      // wrap: false — DON'T soft-wrap code blocks. `wrap: true` injects
      // `white-space: pre-wrap` inline, which wrapped the wide ASCII
      // architecture diagrams (240 cols) and scrambled the box-drawing on
      // every viewport. With wrap off, blocks keep their lines intact and
      // scroll horizontally instead (the `.docs__body pre` CSS sets
      // `overflow-x: auto`), which is the standard code-block behaviour.
      wrap: false,
    },
  },
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      // Treat the home + per-product pages as higher-priority entries;
      // docs + changelog inherit the default.
      serialize(item) {
        const url = item.url;
        if (url === 'https://casualoffice.org/') return { ...item, priority: 1.0, changefreq: 'weekly' };
        if (
          url === 'https://casualoffice.org/casual-sheets/' ||
          url === 'https://casualoffice.org/casual-docs/'
        ) return { ...item, priority: 0.9, changefreq: 'weekly' };
        if (url === 'https://casualoffice.org/casual-desktop/')
          return { ...item, priority: 0.6, changefreq: 'monthly' };
        return item;
      },
    }),
  ],
});
