import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

// Casual Office — schnsrw.live.
// Astro static build. Output goes to dist/; GitHub Pages serves that
// directory via .github/workflows/pages.yml.
//
// Sitemap is auto-generated by @astrojs/sitemap from the routes Astro
// emits. Lastmod is filled in from each page's frontmatter or build time.
// The robots.txt at public/robots.txt references sitemap-index.xml.
export default defineConfig({
  site: 'https://schnsrw.live',
  trailingSlash: 'always',
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      // Treat the home + per-product pages as higher-priority entries;
      // docs + changelog inherit the default.
      serialize(item) {
        const url = item.url;
        if (url === 'https://schnsrw.live/') return { ...item, priority: 1.0, changefreq: 'weekly' };
        if (
          url === 'https://schnsrw.live/casual-sheets/' ||
          url === 'https://schnsrw.live/casual-editor/'
        ) return { ...item, priority: 0.9, changefreq: 'weekly' };
        if (url === 'https://schnsrw.live/casual-desktop/')
          return { ...item, priority: 0.6, changefreq: 'monthly' };
        return item;
      },
    }),
  ],
});
